export class PersonaModel {
  constructor(public nombre: string,
              public edad: string,
              public sexo: string,
              public edoCivil: string,
              public estudios: string,
              public ocupacion: string,
              public departamento: string,
              public puesto: string,
              public contratacion: string,
              public personal: string,
              public jornada: string,
              public rotacion: string,
              public expActual: string,
              public expTotal: string,
              public folio: string,
              public quest1: string,
              public quest2: string,
              public quest3: string,
              public quest4: string,
              public quest5: string,
              public atencionQ1: boolean,
              public calificacion1: number,
              public calificacion2: number,
              public calificacion3: number,
              public id: string) {}
}
